//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_order
    {
        public int id_order { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> id_products { get; set; }
        public Nullable<System.DateTime> date_buy { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<bool> states { get; set; }
        public Nullable<System.DateTime> date_deli { get; set; }
        public string name_customer { get; set; }
        public string address_customer { get; set; }
        public Nullable<int> phone_customer { get; set; }
        public Nullable<bool> status_paying { get; set; }
        public Nullable<bool> status_deli { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
