//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Web;
    using System.Data.Entity.ModelConfiguration.Conventions;
    
    public partial class webClothesEntities : DbContext
    {
        public webClothesEntities()
            : base("name=webClothesEntities")
        {
        }
        public DbSet <customer> customers { get; set; }        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<customer>().ToTable("customer");
            modelBuilder.Conventions.Remove<PluralizingEntitySetNameConvention>();
            base.OnModelCreating(modelBuilder);
        }
    
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<constract> constracts { get; set; }
        public virtual DbSet<customer_order> customer_order { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
    }
}
