//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using System.Web;   
    using System.Data.Entity.ModelConfiguration.Conventions;

    public partial class webClothesEntities : DbContext
    {
        public webClothesEntities()
            : base("name=webClothesEntities")
        {
        }
        public DbSet<customers_login> customers_Logins { get; set; }
        public DbSet<customers_register> customers_Registers { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //Database.SetInitializer<demoEntities>(null);
            modelBuilder.Entity<customers_login>().ToTable("customer_login");
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.Entity<customers_register>().ToTable("customer_register");
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            base.OnModelCreating(modelBuilder);


        }
    
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<constract> constracts { get; set; }
        public virtual DbSet<customer_order> customer_order { get; set; }
        public virtual DbSet<customers_login> customers_login { get; set; }
        public virtual DbSet<customers_register> customers_register { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
    }
}
